src/Entity/Books.php
<?php

namespace App\Entity;

use App\Repository\BooksRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BooksRepository::class)]
class Books
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $summary = null;

    #[ORM\Column(length: 255)]
    private ?string $edition = null;

    #[ORM\Column(length: 255)]
    private ?string $author = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $publication_year = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): static
    {
        $this->summary = $summary;

        return $this;
    }

    public function getEdition(): ?string
    {
        return $this->edition;
    }

    public function setEdition(string $edition): static
    {
        $this->edition = $edition;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getPublicationYear(): ?\DateTimeInterface
    {
        return $this->publication_year;
    }

    public function setPublicationYear(\DateTimeInterface $publication_year): static
    {
        $this->publication_year = $publication_year;

        return $this;
    }
}

src/Form/BooksType.php
<?php

namespace App\Form;

use App\Entity\Books;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BooksType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('summary')
            ->add('edition')
            ->add('author')
            ->add('image')
            ->add('publication_year')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Books::class,
        ]);
    }
}

src/Controller/BooksController.php
<?php

namespace App\Controller;

use App\Entity\Books;
use App\Form\BooksType;
use App\Repository\BooksRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/books')]
class BooksController extends AbstractController
{
    #[Route('/', name: 'books', methods: ['GET'])]
    public function index(BooksRepository $booksRepository): Response
    {
        return $this->render('books/index.html.twig', [
            'books' => $booksRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_books_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $book = new Books();
        $form = $this->createForm(BooksType::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($book);
            $entityManager->flush();

            return $this->redirectToRoute('books', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('books/new.html.twig', [
            'book' => $book,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_books_show', methods: ['GET'])]
    public function show(Books $book): Response
    {
        return $this->render('books/show.html.twig', [
            'book' => $book,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_books_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Books $book, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(BooksType::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('books', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('books/edit.html.twig', [
            'book' => $book,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_books_delete', methods: ['POST'])]
    public function delete(Request $request, Books $book, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$book->getId(), $request->request->get('_token'))) {
            $entityManager->remove($book);
            $entityManager->flush();
        }

        return $this->redirectToRoute('books', [], Response::HTTP_SEE_OTHER);
    }
}

templates/books/_delete_form.html.twig
<form method="post" action="{{ path('app_books_delete', {'id': book.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ book.id) }}">
    <button class="btn">Delete</button>
</form>

templates/books/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Books{% endblock %}

{% block body %}
    <h1>Edit Books</h1>

    {{ include('books/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_books_index') }}">back to list</a>

    {{ include('books/_delete_form.html.twig') }}
{% endblock %}

templates/books/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Books index{% endblock %}

{% block body %}
    <h1>Books index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Summary</th>
                <th>Edition</th>
                <th>Author</th>
                <th>Image</th>
                <th>Publication_year</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for book in books %}
            <tr>
                <td>{{ book.id }}</td>
                <td>{{ book.title }}</td>
                <td>{{ book.summary }}</td>
                <td>{{ book.edition }}</td>
                <td>{{ book.author }}</td>
                <td>{{ book.image }}</td>
                <td>{{ book.publicationYear ? book.publicationYear|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_books_show', {'id': book.id}) }}">show</a>
                    <a href="{{ path('app_books_edit', {'id': book.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_books_new') }}">Create new</a>
{% endblock %}

templates/books/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Books{% endblock %}

{% block body %}
    <h1>Create new Books</h1>

    {{ include('books/_form.html.twig') }}

    <a href="{{ path('app_books_index') }}">back to list</a>
{% endblock %}

templates/books/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Books{% endblock %}

{% block body %}
    <h1>Books</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ book.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ book.title }}</td>
            </tr>
            <tr>
                <th>Summary</th>
                <td>{{ book.summary }}</td>
            </tr>
            <tr>
                <th>Edition</th>
                <td>{{ book.edition }}</td>
            </tr>
            <tr>
                <th>Author</th>
                <td>{{ book.author }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ book.image }}</td>
            </tr>
            <tr>
                <th>Publication_year</th>
                <td>{{ book.publicationYear ? book.publicationYear|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_books_index') }}">back to list</a>

    <a href="{{ path('app_books_edit', {'id': book.id}) }}">edit</a>

    {{ include('books/_delete_form.html.twig') }}
{% endblock %}